version: '3.9'

services:
  arbi:
    build: ./app
    container_name: arbi
    restart: always
    depends_on:
      - database
  
  database:
    image: postgres:14.2-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - arbi:/var/lib/postgres/arbi
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5433:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    restart: always

volumes:
  arbi: