FROM golang:1.18-alpine AS build

ARG GCP_PROJECT_ID
ARG BINANCE_API_KEY
ARG BINANCE_SECRET_KEY

ENV GCP_PROJECT_ID=$GCP_PROJECT_ID
ENV BINANCE_API_KEY=$BINANCE_API_KEY
ENV BINANCE_SECRET_KEY=$BINANCE_SECRET_KEY

RUN mkdir /src

WORKDIR /src

COPY . .

RUN go mod download

RUN go build -o arbi



FROM alpine:latest

RUN mkdir config

COPY --from=build /src/arbi .

COPY --from=build /src/config/config.yml ./config

CMD ./arbi