FROM golang:1.18-alpine AS build

RUN mkdir /src

WORKDIR /src

COPY . .

RUN go mod download

RUN go build -o arbi



FROM alpine:latest

ARG GCP_PROJECT_ID
ARG BINANCE_API_KEY
ARG BINANCE_SECRET_KEY

ENV GCP_PROJECT_ID=$GCP_PROJECT_ID
ENV BINANCE_API_KEY=$BINANCE_API_KEY
ENV BINANCE_SECRET_KEY=$BINANCE_SECRET_KEY

RUN mkdir /config

COPY --from=build /src/arbi .

COPY --from=build /src/config/config.dev.yml ./config/config.yml

COPY --from=build /src/credentials.json .

CMD ./arbi