name: Build and push image to GAR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY_LOCATION: ap-northeast-1
      ECR_REPOSITORY: 263752112305.dkr.ecr.ap-northeast-1.amazonaws.com/arbi
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6

      - name: Set up Docker meta
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.ECR_REPOSITORY }}/arbi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REPOSITORY_LOCATION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@b874a33292cc9887d2e80bc63f6f1a11fccb4a7b

      - name: Build the Docker image and push it to the Amazon ECR
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          context: .
          file: Dockerfile.prod
          push: true
          build-args: |
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}
            BINANCE_SECRET_KEY=${{ secrets.BINANCE_SECRET_KEY }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}